Mysite/urls.py
from django.contrib import admin
from django.urls import path, include

import myapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
]

myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'
urlpatterns = [
    path('',views.HomeView.as_view(),name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
import os
from django.urls import reverse

# Create your models here.
def path_and_rename(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.pk:
        filename = 'User_Profile_Pictures/{}.{}'.format(instance.pk, ext)
    return os.path.join(upload_to, filename)


class UserProfileInfo(models.Model):

    #creating a relationship with user class (not inheriting)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #adding additional attributes
    bio = models.CharField(max_length=500)
    profile_pic = models.ImageField(upload_to=path_and_rename, verbose_name="Profile Picture", blank=True)
    teacher = 'teacher'
    student = 'student'
    parent = 'parent'
    user_types = [
        (teacher, 'teacher'),
        (student, 'student'),
        (parent, 'parent'),
    ]
    user_type = models.CharField(max_length=10, choices=user_types, default=student)

    def __str__(self):
        return self.user.username

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from myapp.models import UserProfileInfo

class UserForm(UserCreationForm):
    email = forms.EmailField()

    class Meta():
        model = User
        fields = ('username','first_name','last_name', 'email', 'password1', 'password2')

        # widgets = {
        # "password":"forms.PasswordInput()",
        # }

        labels = {
        'password1':'Password',
        'password2':'Confirm Password'
        }

class UserProfileInfoForm(forms.ModelForm):
    bio = forms.CharField(required=False)
    teacher = 'teacher'
    student = 'student'
    parent = 'parent'
    user_types = [
        (student, 'student'),
        (parent, 'parent'),
    ]
    user_type = forms.ChoiceField(required=True, choices=user_types)

    class Meta():
        model = UserProfileInfo
        fields = ('bio', 'profile_pic', 'user_type')

myapp/views.py
from django.shortcuts import render
from myapp.forms import UserForm, UserProfileInfoForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from .models import UserProfileInfo
from django.views.generic import TemplateView
from django.http import HttpResponse, HttpResponseRedirect


# Create your views here.
def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT IS DEACTIVATED")
        else:
            return HttpResponse("Please use correct id and password")
            # return HttpResponseRedirect(reverse('register'))

    else:
        return render(request, 'myapp/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            # user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'myapp/registration.html',
                            {'registered':registered,
                             'user_form':user_form,
                             'profile_form':profile_form})    

class HomeView(TemplateView):
    template_name = 'myapp/index.html'

  

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <title>{%block title%}{%endblock%}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/master_css.css' %}">

  </head>
  <body>
    <!-- navigation bar -->
              <nav class="navbar navbar-expand-lg  navbar-light bg-light fixed-top scrolling-navbar">
                <div class="container" >
                      <a class="navbar-brand" href="{% url 'myapp:index' %}" style="color:#ff5722;" >Home</a>
                      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                           aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                           <span class="navbar-toggler-icon"></span>
                       </button>
                      <div class="collapse navbar-collapse" id="basicExampleNav" >
                        <ul class=" navbar-nav  mr-auto smooth-scroll " >
                                {% if user.is_superuser %}
                                <li class="nav-item ">
                                   <a class="nav-link" href="{% url 'admin:index' %}">Admin</span> </a>
                                </li>
                                {%endif%}
                                {% if user.is_authenticated %}
                                    <li class="nav-item  ">
                                     <a class="nav-link" href="{% url 'myapp:user_logout' %}">Logout</a>
                                    </li>
                                {% else %}
                                    <li class="nav-item ">
                                        <a class="nav-link" href="{% url 'myapp:user_login' %}">Login</a>
                                    </li>
                                    <li class="nav-item " >
                                       <a class="nav-link" href="{% url 'myapp:register' %}">Register</span> </a>
                                    </li>
                                {% endif %}
                               
                                <li class="nav-item">
                                   <a class="nav-link" href="/">GitHub</a>
                                </li>
                                <li class="nav-item">
                                   <a class="nav-link" href="/">Youtube</a>
                                </li>

                        </ul>
                      </div>
                </div>
              </nav>
          {% block image_block %}
          {% endblock %}



    <footer class="page-footer" style="background-color:#b2ebf2;">
      <div class="container">
        <div class="row mt-4">
                  <div class="col-md-4 mt-4">
                            <h3>About Us</h3> <br>
                            
                  </div>
                  <div class="col-md-4 mt-4">
                            <h3>Other Useful Stuff</h3>
                            <ul>
                              <li>Item 1</li>
                              <li>Item 2</li>
                              <li>Item 3</li>
                            </ul>
                  </div>
                  <div class="col-md-4 mt-4">
                            <h3>Contact Us</h3>
                            <ul>
                              <li>Address: Nearest you, state, country</li>
                              <li>contact number</li>
                            </ul>
                  </div>
        </div>
        
      </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
  </body>
</html>

templates/myapp/index.html
{% extends 'base.html'  %}
{% load static %}
{%block title %}index page{% endblock%}

{% block image_block%}
<header>
<!--Image and mask-->
          <div id="intro" class="container-fluid d-flex align-items-center justify-content-center h-100">
            <div class="row d-flex justify-content-center text-center">
              <div class="col-md-10 text-white">
                <!-- heading -->
                <h2 class="display-4 font-weight-bold white-text  p-5 mb-2" style="color:#ff5722;" > Start Learning </h2>

                <!-- divider -->
                <hr style="color:#ff5722;">

                
                <a href="/"> <button type="button" class="btn" style="color:#ff5722;border-color:#ff5722;"> Start Now</button> </a>

                
              </div>
            </div>
          </div>

</header>
{%endblock%}

templates/myapp/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Login{% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > Login </h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li class="disabled-text" >Login</li>
          </ul>
        </div>

       
   
  </div>
</header>
{% endblock %}

{% block content %}

<section class="text-center mt-4">
              <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">Login To Explore</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8">
                </div>
              </div>
              <div class="row d-flex justify-content-center mb-4">
                <form action="{% url 'user_login' %}" method="post">
                  <div class="form-group">


                  {% csrf_token %}
                  <div class="col-md-12">
                    <div class="row">


                  <label for="username">Username:</label>
                  <input type="text" name="username" placeholder="Username" class="form-control">

                  <label for="password">Password:</label>
                  <input type="password" name="password" class="form-control">
                  </div>
                  <div class="row justify-content-center">
                      <input type="submit" value="Login" class="btn btn-success btn-lg mt-3">
                  </div>
                  </div>
                  </div>
                </form>
              </div>
</section>
{%endblock%}

templates/myapp/registration.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Register{% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > Registration </h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li class="disabled-text" >Registration</li>
          </ul>
        </div>

        
       
  </div>
</header>
{% endblock %}


{% block content %}

<section class="text-center mt-4">
              <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">Registration</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
              
              </div>
              <div class="row d-flex justify-content-center mb-4">

              </div>
</section>

  {% if registered %}
    <h1>Thank you for registering</h1>
  {% else %}
      <h3>Fill the form: </h3>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form|crispy }}
        {{ profile_form|crispy }}
        <div class="row justify-content-center">
        <div class="col-md-6">
        <input type="submit" value="Register" class="btn btn-primary btn-block">
        </div>
        </div>
      </form>
  {% endif %}
{%endblock%}